### ISSUE TITLE
Icons not shown

### ISSUE THREAD

**Issue by theScythe** [dbrgn/passwortpranger#14]
Font from origin 'https://passwortpranger.s3.amazonaws.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.passwortpranger.ch' is therefore not allowed access.

**Comment by aebersold** [comment]
is it possible use http w/o ssl? that would fix the issue

**Comment by dbrgn** [comment]
Related to #13.

A Passwortpranger without TLS sucks a little bit :)

**Comment by dbrgn** [comment]
Anscheinend fehlt noch eine CORS Konfiguration: http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors

**Comment by dbrgn** [comment]
@theScythe kannst du das bei gelegenheit mal anschauen? :)

**Comment by theScythe** [comment]
das sollte das problem lösen:

    <CORSConfiguration>
     <CORSRule>
       <AllowedOrigin>http://*.passwortpranger.ch</AllowedOrigin>
       <AllowedMethod>GET</AllowedMethod>
       <MaxAgeSeconds>3000</MaxAgeSeconds>
       <AllowedHeader>*</AllowedHeader>
     </CORSRule>
     <CORSRule>
       <AllowedOrigin>http://passwortpranger.ch</AllowedOrigin>
       <AllowedMethod>GET</AllowedMethod>
       <MaxAgeSeconds>3000</MaxAgeSeconds>
       <AllowedHeader>*</AllowedHeader>
     </CORSRule>
     <CORSRule>
       <AllowedOrigin>https://*.passwortpranger.ch</AllowedOrigin>
       <AllowedMethod>GET</AllowedMethod>
       <MaxAgeSeconds>3000</MaxAgeSeconds>
       <AllowedHeader>*</AllowedHeader>
     </CORSRule>
     <CORSRule>
       <AllowedOrigin>https://passwortpranger.ch</AllowedOrigin>
       <AllowedMethod>GET</AllowedMethod>
       <MaxAgeSeconds>3000</MaxAgeSeconds>
       <AllowedHeader>*</AllowedHeader>
     </CORSRule>
    </CORSConfiguration>
